#!/usr/bin/env npx tsx
/**
 * Cross-validate Carm geomin rotation against R GPArotation::geominQ
 * Tests both delta = 0.01 (GPArotation default) and delta = 0.001 (lavaan default)
 *
 * R reference generated by:
 *   Rscript validation/r-reference/fa-geomin-ref.R
 */
import { readFileSync, existsSync } from 'fs'
import { runEFA } from 'carm'

// Load synthetic datasets
const dataPath = existsSync('validation/data/fa-crossval-data.json')
  ? 'validation/data/fa-crossval-data.json'
  : 'tmp/fa-crossval-data.json'

const datasets = JSON.parse(
  readFileSync(dataPath, 'utf-8')
).datasets as Array<{
  id: number
  params: { n: number; k: number }
  data: number[][]
  variableNames: string[]
}>

// Permutation + sign matching
function permutations(n: number): number[][] {
  if (n === 1) return [[0]]
  const result: number[][] = []
  const sub = permutations(n - 1)
  for (let i = 0; i < n; i++) {
    for (const perm of sub) {
      result.push([i, ...perm.map(x => x >= i ? x + 1 : x)])
    }
  }
  return result
}

function bestMAE(cLoad: number[][], rLoad: number[][], p: number, k: number): {
  mae: number; perm: number[]; signs: number[]
} {
  let bestMae = Infinity
  let bestPerm: number[] = []
  let bestSigns: number[] = []

  for (const perm of permutations(k)) {
    for (let signMask = 0; signMask < (1 << k); signMask++) {
      const signs = Array.from({ length: k }, (_, j) =>
        (signMask & (1 << j)) ? -1 : 1
      )
      let sumAE = 0
      for (let i = 0; i < p; i++) {
        for (let j = 0; j < k; j++) {
          sumAE += Math.abs(
            cLoad[i]![perm[j]!]! * signs[j]! - rLoad[i]![j]!
          )
        }
      }
      const mae = sumAE / (p * k)
      if (mae < bestMae) {
        bestMae = mae
        bestPerm = perm
        bestSigns = signs
      }
    }
  }
  return { mae: bestMae, perm: bestPerm, signs: bestSigns }
}

// ── Test a single delta value ────────────────────────────────────────────────

function runDeltaTests(delta: number, refPath: string): { passed: number; failed: number } {
  if (!existsSync(refPath)) {
    console.log(`  Skipping: ${refPath} not found (run R reference script first)`)
    return { passed: 0, failed: 0 }
  }

  const rRef = JSON.parse(
    readFileSync(refPath, 'utf-8')
  ) as Array<{
    id: number; n: number; p: number; k: number
    loadings: number[][]; phi: number[][]; converged: boolean
  }>

  const refMap = new Map(rRef.map(r => [r.id, r]))
  let passed = 0, failed = 0
  const threshold = 0.05

  for (const ds of datasets) {
    const ref = refMap.get(ds.id)
    if (!ref) continue

    const result = runEFA(ds.data, {
      nFactors: ds.params.k,
      extraction: 'ml',
      rotation: 'geomin',
      geominDelta: delta,
      variableNames: ds.variableNames,
    })

    const cLoad = result.loadings.map(r => [...r])
    const { mae } = bestMAE(cLoad, ref.loadings, ref.p, ref.k)

    const pass = mae <= threshold
    if (pass) passed++; else failed++

    const marker = pass ? '\u2713' : '\u2717'
    console.log(
      `[${String(ds.id).padStart(3)}] n=${ref.n} p=${ref.p} k=${ref.k} ${marker} loadMAE=${mae.toFixed(4)}`
    )
  }

  return { passed, failed }
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log('=== Geomin cross-validation (delta = 0.01, GPArotation default) ===')
const r1 = runDeltaTests(0.01, existsSync('validation/data/fa-geomin-ref.json')
  ? 'validation/data/fa-geomin-ref.json'
  : 'tmp/fa-geomin-ref.json')
console.log(`  Result: ${r1.passed} passed, ${r1.failed} failed\n`)

console.log('=== Geomin cross-validation (delta = 0.001, lavaan default) ===')
const r2 = runDeltaTests(0.001, existsSync('validation/data/fa-geomin-d001-ref.json')
  ? 'validation/data/fa-geomin-d001-ref.json'
  : 'tmp/fa-geomin-d001-ref.json')
console.log(`  Result: ${r2.passed} passed, ${r2.failed} failed\n`)

// ── Real dataset tests ───────────────────────────────────────────────────────

const realCsvPath = '/Users/mohammedsaqr/Downloads/rraw_dataaw_data.csv'
if (existsSync(realCsvPath)) {
  console.log('=== Real dataset geomin ===')
  const csv = readFileSync(realCsvPath, 'utf-8')
  const lines = csv.trim().split('\n')
  const header = lines[0]!.split(',')
  const realData = lines.slice(1).map(l => l.split(',').map(Number))
  const threshold = 0.05

  for (const delta of [0.01, 0.001]) {
    const suffix = delta === 0.01 ? '' : '-d001'
    const refFile = existsSync(`validation/data/fa-geomin-real${suffix}-ref.json`)
      ? `validation/data/fa-geomin-real${suffix}-ref.json`
      : `tmp/fa-geomin-real${suffix}-ref.json`

    if (!existsSync(refFile)) {
      console.log(`  Skipping delta=${delta}: ${refFile} not found`)
      continue
    }

    console.log(`\n--- delta = ${delta} ---`)
    const realRef = JSON.parse(
      readFileSync(refFile, 'utf-8')
    ) as Record<string, { k: number; loadings: number[][]; phi: number[][] }>

    for (const kStr of ['3', '5']) {
      const rr = realRef[kStr]!
      const result = runEFA(realData, {
        nFactors: rr.k,
        extraction: 'ml',
        rotation: 'geomin',
        geominDelta: delta,
        variableNames: header,
      })

      const cLoad = result.loadings.map(r => [...r])
      const { mae } = bestMAE(cLoad, rr.loadings, header.length, rr.k)
      const pass = mae <= threshold
      console.log(`  k=${rr.k}: ${pass ? '\u2713' : '\u2717'} loadMAE=${mae.toFixed(4)}`)
    }
  }
} else {
  console.log('(Skipping real dataset tests — CSV not found)')
}

// ── Summary ──────────────────────────────────────────────────────────────────
const totalPassed = r1.passed + r2.passed
const totalFailed = r1.failed + r2.failed
console.log(`\n=== TOTAL: ${totalPassed} passed, ${totalFailed} failed ===`)
if (totalFailed > 0) process.exit(1)
